### PR TITLE
Fix for Rails 3.2 initialization

### PR DESCRIPTION
**Pull request by wflanagan**
Fixes problem with initialization, in what I BELIEVE is a Rails 3.xx compatibility issue.

### CODE REVIEW

**Comment by ACPK** [comment]
Is this still an issue?

**Comment by wflanagan** [comment]
Hi Andrew,

It still seems to be a problem. Our branch/patch fixes it though, at least
in our Rails 3.2 app.

WF

**Comment by ankane** [comment]
Hi William, thanks for the PR. What's the error you get without the patch?

**Comment by ankane** [comment]
I believe it's a Ruby 2.0 issue, from what was reported in #68

**Pull request merged**
