### PR TITLE
Track open and click IPs

### PR DESCRIPTION
**Pull request by cmer**

### CODE REVIEW

**Comment by cmer** [comment]
Hi, I submitted 2 pretty legit pull requests (this and #85) and was wondering if they could be merged. I've been using them in production without any issues. Thanks!

**Comment by KMHouk** [comment]
+1 -- this would be a valuable addition to the gem

**Comment by cyrill62** [comment]
👍

**Comment by ankane** [comment]
Hey @cmer, thanks for another PR 👍 You should be able to accomplish this pretty easily with a custom event subscriber (probably what you're doing now), so don't think it makes sense to include as part of the gem.

**Pull request closed without merging**
