### PR TITLE
Use `Addressable::URI.heuristic_parse` to handle URIs with missing info

### PR DESCRIPTION
**Pull request by kartikluke**
http://www.rubydoc.info/gems/addressable/Addressable/URI.heuristic_parse

For #88

### CODE REVIEW

**Comment by ankane** [comment]
Hey @kartikluke, thanks for the PR 👍 

I don't fully understand the differences between `parse` and `heuristic_parse` ([code here](https://github.com/sporkmonger/addressable/blob/6aa1b8a1fa3eb2fed7e02ae73e566855ce0f165d/lib/addressable/uri.rb#L162), so a bit worried to change what seems to be working well.

My recommendation would be to make sure any links devs want tracked have a protocol.

**Comment by kartikluke** [comment]
@ankane My use case has user generated content which is why I proposed this pull request. I understand that it may give non standard behavior for people who are using it on the development side.

**Comment by ankane** [comment]
Hey @kartikluke, sorry the discussion stalled. I'm happy to add once we have tests for things like mailto links, mobile app links, etc. Until then, going to mark this as `waiting`.

**Comment by kartikluke** [comment]
@ankane I've added in the tests.  

Testing that:
- the heuristic parse works
- ignores mailto and app links
- doesn't have unexpected side-effects with the other features

**Comment by ankane** [comment]
This is beautiful. Thanks @kartikluke 💯

**Comment by kartikluke** [comment]
@ankane You're welcome. This gem has been really useful. If there are any other issues you'd like to tackle I'd be happy to contribute.

**Comment by ankane** [comment]
Thanks @kartikluke. I'm planning to do a major update sometime in the next few weeks to move tracking to an interceptor and add a custom method for writing to any data store. I think it'll change the code significantly, so probably best to wait until then for any bigger contributions.

**Pull request merged**
