### PR TITLE
pull req

### PR DESCRIPTION
**Pull request by jcarreti**
This small change allows to keep um_params persisted. Very useful for stats and charting purposes.. We already use that on production env.

### CODE REVIEW

**Comment by ankane** [comment]
Awesome, thanks @jcarreti!

**Comment by jcarreti** [comment]
Thank you! It's an awesome gem, congrats!

**Comment by guyisra** [comment]
any chance to add a bit about this in the readme?

**Comment by ankane** [comment]
@guyisra what'd you have in mind?

**Comment by guyisra** [comment]
I think people who will upgrade will want to know that new columns are needed, since the definition for those columns are only in the generator for first time installation. 

also would be nice to know how @jcarreti uses it in production (use cases, etc). Could this be a sufficient solution for #19 ?

**Comment by ankane** [comment]
Added a note to the readme.

**Pull request merged**
