### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ruslankhaertdinov**

### CODE REVIEW

**Comment by ankane** [comment]
Hey @ruslankhaertdinov, thanks for the PR. Happy add instructions for testing. I typically add it to the Contributing section for my projects. Here's [an example](https://github.com/ankane/blind_index#contributing).

The ability to call `track` inside an action is not recommended anymore, so don't want to include it in the readme.

**Comment by ruslankhaertdinov** [comment]
@ankane thank you, I'll update PR shortly.

**Comment by ruslankhaertdinov** [comment]
@ankane done.

**Comment by ankane** [comment]
Awesome, thanks 👍

**Pull request merged**
